export const LOAD_HOME = 'LOAD_HOME';
export const LOAD_HOME_INIT = 'LOAD_HOME_INIT';
export const ERROR = 'LOAD_HOME_ERROR';

export const LOAD_MASTER = 'LOAD_MASTER';
export const LOAD_MASTER_INIT = 'LOAD_MASTER_INIT';
export const GOPAGE_ANIVERSARIANTES_MASTER = 'GOPAGE_ANIVERSARIANTES_MASTER';
export const GOPAGE_ANIVERSARIANTES_START= 'GOPAGE_ANIVERSARIANTES_START';
export const GOPAGE_ANIVERSARIANTES_FIM = 'GOPAGE_ANIVERSARIANTES_FIM';
export const ERROR_MASTER = 'LOAD_MASTER_ERROR';


export const LOAD_PROVIDER_INIT = 'LOAD_PROVIDER_INIT';
export const LOAD_PROVIDER = 'LOAD_PROVIDER_INIT';